### ISSUE TITLE
"My decklists" don't load my decklists. It just looks blank. I can't create or modify decklists.

### ISSUE THREAD

**Issue by dito-val** [Null-Signal-Games/netrunnerdb#946]
<img width="1724" height="704" alt="Image" src="https://github.com/user-attachments/assets/a23e4267-0031-49a9-b594-b5b3ac88b3eb" />

**Comment by Cwmcmahon** [comment]
I ran into this today, using Zen Browser on my laptop. It wasn't an issue with Chromium on my laptop or Firefox on my Android phone.

**Comment by plural** [comment]
This will happen if you are not logged in.  The "My decklists" search under decklists is not a protected page, so auth is not required.  If you use "My decks" in the navigation it will take you to a login page if you aren't logged in.
 
We should fix that and redirect to the login page.  I've filed #949 to track that fix. 

Thanks for reporting this.

**Comment by dito-val** [comment]
[image: image.png]

My decklists don't appear even when I'm logged in.

Thank you for your help.

**Comment by plural** [comment]
would you please open your developer console in your browser and let us know if any errors are in there?  

If you go to "My Decks" do you actually have decks made already that load?

**Comment by dito-val** [comment]
I don't know what a developer console is, but I don't know if that message
is for me.

I did have decks in "my decklist" before. I've also tried copying an
existing deck in my decklists to see if it appears, but it doesn't.

When I sign up for a tournament in cobra I can see the decklists in cobra
to upload. I can even click to modify the deck in NDB and it takes me to
the deck there and I can change it. But I cannot access directly from NDB
nor can I create new decks.

Thank you for your help.

**Comment by dito-val** [comment]
Hi,

This problem still persists, I cannot access my decks in NetrunnerDB.

Thank you for your help,
Diana
